### ISSUE TITLE
Invalid arguments for luma; different result compared to default avs resizer

### ISSUE THREAD

**Issue by TbtBI** [jpsdr/ResampleMT#1]
Hi.

Thanks for your filters.

Tested the latest version 2.1.2.
When resizing width the result is different compared to default avs resizer:
```
#1920x1080 source
s=last
spline36Resize(1918,1080,0,0,0,0)
a=last
s
Spline36resizeMT(1918,1080,0,0,0,0)
Compare(a, channels="yuv")
```
When resizing height - no difference:
```
#1920x1080 source
s=last
spline36Resize(1920,1000,0,0,0,0)
a=last
s
Spline36resizeMT(1920,1000,0,0,0,0)
Compare(a, channels="yuv")
```

When cropping only luma plane, it gives error "Invalid arguments....":
```
#1920x1080 source
extracty()
spline36ResizeMT(1920,1078,0,1,0,-1)
```
Default avs resizer is ok, Processing only u/v planes is ok.

**Comment by jpsdr** [comment]
Ouups.... Very sorry !! I've missed this one.
What avisynth version are you using ?

**Comment by TbtBI** [comment]
[The latest Avisynth+ x64.](https://github.com/pinterf/AviSynthPlus/releases)

Btw version 2.2.0 requires libmmd.dll. Could you build it static?

**Comment by jpsdr** [comment]
I've reproduced, i'll investigate when i'll have time, unfortunately not right now...
No, i don't build static, the libmmd.dll i think it's for the intel release ?
Get the redistribuables, i've provided the links in the readme.

**Comment by TbtBI** [comment]
Thanks.

**Comment by jpsdr** [comment]
I don't know if i'll be able to solve the difference part issue... I've made some quick tests, when i'll have more time i have some tests i have in mind, i'll check between the codes of original and mine, but i'm note sure if i'll find something. I've reproduced your issue, but, when i've made the same test with a DVD video input, with size of 720x480, i have the opposite results...
```
s=last
#Spline36Resize(720,464,0,0,0,0)
spline36Resize(704,480,0,0,0,0)
a=last
s
#Spline36resizeMT(720,464,0,0,0,0)
Spline36resizeMT(704,480,0,0,0,0)
Compare(a,channels="yuv")
```

The "invalid parameter" i'll investigate first as soon as i've time, there is no reason for this to not be able to fix it.

**Comment by jpsdr** [comment]
Issue not trigged in float mode.
```
ConvertBits(32)
a=BicubicResize(1904,1000,0,0,0,0)
b=BicubicresizeMT(1904,1000,0,0,0,0)
Subtract(a,b)
ConvertBits(8)
Levels(127, 1, 129, 0, 255)
```
This is for me a good thing, because it means that all the coefficients calculations and similar stuff are made properly. There is probably just a small difference between my code and the original code in the rounding process in case of integer, no big deal even if it; stays like this.

**Comment by TbtBI** [comment]
Thanks for the update.

**Comment by jpsdr** [comment]
Crop issue found, fix in next release.

**Comment by jpsdr** [comment]
Will make some investigation and check tomorrow about the difference, but i don't intend to spend more time than my investigation tomorrow if i found nothing.

**Comment by jpsdr** [comment]
Float, 16,14,12, and 10 bits produce indentical results, only 8 bits is different.

**Comment by pinterf** [comment]
One difference is that avs version is not limiting the output to 16-235/16-240?

**Comment by jpsdr** [comment]
Not enabled by default and should also occurs on 16-10 bits if it was that, but still something to check as 8 bits as specific code different from 16-10.
These results confirm for me that the position and coeff array made in the resample_function are good.

**Comment by TbtBI** [comment]
```
#1920x1080 source
s=last
spline36Resize(1800,1080,0,0,0,0) 
a=last
s
Spline36resizeMT(1800,1080,0,0,0,0)
Compare(a, channels="yuv")
```
No difference with width 1800 but width 1820, for example, still have difference.

**Comment by pinterf** [comment]
Yep. When compared with source
```
#1920x1080 source
c=Colorbars(width=1920, height=1080, pixel_type = "YV24").Limiter()/*.GreyScale*/
a=c.spline36Resize(1918,1080,0,0,0,0)#.Limiter()
b=c.Spline36resizeMT(1918,1080,0,0,0,0)#.Limiter()
Subtract(a,b)
ConvertBits(8)
StackVertical(Levels(127, 1, 129, 0, 255),a,b)
```
to be sure I'm using Limiter to rule out limiting differences, because ColorBars test screen uses sub 16 values

I can see two vertical lines as a difference, the left one is at the edge of a dark/white block.

**Comment by jpsdr** [comment]
I'm loosing hairs... :(
I've made a debug build of my code disabling all CPU accelerations, so it goes only on the pure C code part.
Source 1920x1080.
=> 1912x1080 : Identical.
=> 1914x1080 : Identical.
=> 1920x1000 : Differences only in 8 bits, identical 10-16bits and float.
=> 1912x1000 : Identical only on float, differences in 16 to 8 bits.

I've noticed something odd in VirtualDub output when doing the following with a 720x480 YV12 8 bits source input :
```
s=last
Spline36Resize(720,464,0,0,0,0)
a=last
s
Spline36resizeMT(720,464,0,0,0,0,threads=1)
Compare(a,channels="yuv")
```

**Comment by pinterf** [comment]
Just noting that 8 bit code with SSSE3 and up may give different results due to the use of _mm_mulhrs_epi16 which has a 'smart' internal pecision and rounding inside.
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#expand=5080,3538,4676,348,5538,5595,5080,3573,3556,5316,3077,3974&text=_mm_mulhrs_epi16
You can probably compare the output of pure SSE2 and C. 
Or you can compare SSSE3 with any same or better processor level.

**Comment by jpsdr** [comment]
The tests seems to show that if there is something, it's when resizing vertical, even if it's not trigged when vertical resizer is used for horizontal resizing (1914x1080).
I'll do some check again tomorrow, but if i found nothing, i won't investigate further for the time being.

**Comment by jpsdr** [comment]
BTW, isn't, in theory
```
program->pixel_coefficient[i*fir_filter_size+k] = short(int((new_value-value)*current_FPScale+0.5));
```
more accurante than
```
program->pixel_coefficient[i*fir_filter_size+k] = short(int(new_value*current_FPScale+0.5)-int(value*current_FPScale+0.5));
```
The second can cumulate two rounding error.

**Comment by pinterf** [comment]
Or the opposite, it can minimize accumulation of error when we examine the coefficients as a whole. I wouldn't touch it.
I recommend looking at the relevant zimg resizer library solution, which I consider a bit more elaborated than the one in actual Avisynth, it uses a bit different way.
https://github.com/sekrit-twc/zimg/blob/master/src/zimg/resize/filter.cpp#L258
and https://github.com/sekrit-twc/zimg/blob/master/src/zimg/resize/filter.cpp#L90

**Comment by jpsdr** [comment]
Interesting, thanks, i'll take a better look later.

**Comment by jpsdr** [comment]
Ok, tests results. First, disabling CPU acceleration was a mistake, i added differences where they were not, as pure C may produce different results than AVX2.
With 1920x1080 input, i've tested :
=> 1920x1000 : Identical, use the AVX2 vertical resizer.
=> 1912x1080 : Identical, use the AVX2 horizontal resizer, notificaly slower in debug mode.
=> 1914x1080 : Different, use the AVX2 vertical resizer. I tested in my code with TurnLeft/ResizeV/TurnRight, and TurnRight/ResizeV/TurnLeft, still different in both cases.
I give up for this specific case, i don't know why it's different, i didn't found any reason why unless TurnLeft/Right change data, but they shouldn't...
Haven't checked in more than 8 bits this one.

=> 1912x1000 : Use AVX2 vertical and horizontal resizer. Different. Changed the order of resize between vertical and horizontal, then identical. In that case, the difference is no big deal, as it's just because of the order if horizontal or vertical is made first.
Nevertheless, i think there was an error in my code, i have:
```
  // ensure that the intermediate area is maximal
  const double area_FirstH = (desample)?subrange_height*vi.width:subrange_height*target_width;
  const double area_FirstV = (desample)?subrange_width*target_height:subrange_width*vi.height;
```
when i think i should have:
```
  // ensure that the intermediate area is maximal
  const double area_FirstH = (desample)?subrange_height*vi.width:subrange_height*target_width;
  const double area_FirstV = (desample)?subrange_width*vi.height:subrange_width*target_height;
```
Didn't have the time to properly test this fix.
That's all i'll do for this, i'll implement the area first fix, and will be done with this for now (unless i have some enlightment).

But, later, i'll take a look at the zimg code.

**Pinterf**
This simple script produces garbage output.
```
a=Colorbars(width=720, height=480, pixel_type = "YV12")
a
Compare(a,channels="yuv")
```

**Comment by pinterf** [comment]
Non-fast_resize with turnleft/verticalresize/turnright is only used for nonplanar colorspaces or with lower-than-SSSE3 processors, such as old packed rgb formats. So basically it is not used much in real life.

(And a cannot see any garbage with that colorbars with AVS+, which avs+ version are you using?)

**Comment by jpsdr** [comment]
2772.
When you open this simple script in VirtualDub, you don't see the vertical lines (1 pixel width) at the bottom of the video ?

**Comment by pinterf** [comment]
That is a graph. See Avisynth.nl Compare doc

**Comment by jpsdr** [comment]
Ah..... My mistake ! I thought it was just writing the informations in the left-top corner.
Ok, thanks.

**Comment by jpsdr** [comment]
While testing the area first fix, i had a revelation !!!
My code
```
bool fast_resize=((env->GetCPUFlags() & CPUF_SSSE3) == CPUF_SSSE3 ) && vi.IsPlanar() && ((SizeH & 3) == 0);

	if (fast_resize && !grey && !isRGBPfamily)
	{
		const int dst_chroma_width = SizeH >> shift;

		if ((dst_chroma_width & 3) != 0) fast_resize = false;
	}  
```
avs+ code
```
bool fast_resize=((env->GetCPUFlags() & CPUF_SSSE3) == CPUF_SSSE3 ) && vi.IsPlanar();
```
It seems i've missed the fact that there was no need anymore to check for appropriate size.
Now output is totaly identical.

**Comment by TbtBI** [comment]
```
#1920x1080 source
#ConvertBits() 10...32
s=last
spline36Resize(1918,1080,0,0,0,0)
ConvertBits(8)
a=last
s
Spline36resizeMT(1918,1080,0,0,0,0)
ConvertBits(8)
Compare(a, channels="yuv")
```
The previous version has identical* output in 10...32-bit. Version 2.2.2 has ~3x smaller error in 8-bit (there is still) and now different* output in 10...16-bit.

```
#1920x1080 source
#ConvertBits() 10...32
s=last
spline36Resize(1920,1000,0,0,0,0)
ConvertBits(8)
a=last
s
Spline36resizeMT(1920,1000,0,0,0,0)
ConvertBits(8)
Compare(a, channels="yuv")
```
The previous version has identical* output in 8...32-bit. Version 2.2.2 has identical* output only in 32-bit.

*identical / *different compared to the default avs+ resizer.
[Here a video sample.](https://www.upload.ee/files/10062279/02__2_.7z.html)

**Comment by jpsdr** [comment]
I've tested with the following
```
#1920x1080 input
ConvertBits(16)
s=last
#Spline36Resize(1920,1000,0,0,0,0)
#Spline36Resize(1912,1080,0,0,0,0)
#Spline36Resize(1914,1080,0,0,0,0)
#Spline36Resize(1912,1000,0,0,0,0)
#Spline36Resize(1914,1000,0,0,0,0)
#Spline36Resize(1916,1000,0,0,0,0)
Spline36Resize(1916,1002,0,0,0,0)
a=last
s
#Spline36resizeMT(1920,1000,0,0,0,0)
#Spline36resizeMT(1912,1080,0,0,0,0)
#Spline36resizeMT(1914,1080,0,0,0,0)
#Spline36resizeMT(1912,1000,0,0,0,0)
#Spline36resizeMT(1914,1000,0,0,0,0)
#Spline36resizeMT(1916,1000,0,0,0,0)
Spline36resizeMT(1916,1002,0,0,0,0)
Compare(a,channels="yuv")
ConvertBits(8)
```
Tested all these resolutions on 8, 10 and 16 bits. All tests produce perfect match, it wasn't the case before. For me this issue is fixed.

**Comment by TbtBI** [comment]
```
#1920x1080 input
ConvertBits(16)
s=last
Spline36Resize(1916,1002,0,0,0,0)
a=last
s
Spline36resizeMT(1916,1002,0,0,0,0)
Compare(a,channels="yuv")
ConvertBits(8)
```
[previous version](https://images2.imgbox.com/9c/e8/n6ncngab_o.png) vs [version 2.2.2](https://images2.imgbox.com/1e/cb/G1VdtHYD_o.png)
What am I doing wrong because I'm seeing bigger difference with the latest version?

**Comment by jpsdr** [comment]
What avs+ version are you using ?
What CPU do you have ? Does it have AVX, AVX2, or just SSE4.2 ?
I don't understand anymore at this point...

**Comment by jpsdr** [comment]
Result with the small video test you've provided [here](http://jpsdr.free.fr/XBMC/Test_Resample.png)

**Comment by TbtBI** [comment]
[avs+ version](https://images2.imgbox.com/c8/9d/xqkXDiNc_o.png)
[CPU](https://images2.imgbox.com/ad/07/7k2d2vAx_o.png)
[2.2.0](https://images2.imgbox.com/f8/ed/JaloBC39_o.png) vs [2.2.2](https://images2.imgbox.com/ca/30/GM3U5j8W_o.png)

**Comment by jpsdr** [comment]
We have the same avs+ version, and both AVX2 CPU.
I have no idea here...
The same script on the same frame of the same video doesn't produce the same result even with both the same avs+ version and CPU AVX2, i'm lost. I realy have no idea...
I don't think it will change something, but just in case, if you can test with the Intel_AVX2 and Intel_AVX2_Broadwell version.
After, i'm sorry but at this point, i've done everything i can think off, and i've the same result on three differents PC.
**Edit**
Forget the Intel version test, when fixing this issue i've used debug, standard and Intel version.
Otherwise, if you can test, does opening the script with VirtualDub also show different frames ? (Don't bother with a picture).

**Comment by TbtBI** [comment]
Both Intel_AVX2 and Intel_AVX2_Broadwell versions have the same output as Release_W7.
I tested on a different PC (CPU AVX only, still Intel) - [2.2.0](https://images2.imgbox.com/e2/d8/LdRArk2C_o.png) (same output on both PCs) vs [2.2.2](https://images2.imgbox.com/ad/a8/WQ6BLt40_o.png) (different output on both PCs)
> ... Otherwise, if you can test, does opening the script with VirtualDub also show different frames ? (Don't bother with a picture).

What do you mean? I opened the script with VirtualDub 1.10.5 test 7 64-bit and it shows different frame numbers and pictures when I go backward and forward through the video.

**Comment by jpsdr** [comment]
In the picture, i didn't recognise the VDub interface, so i thought maybe you used something else, even if it shouldn't mater. BUT !!!!
Arghh...! I've just thougth of testing something... And... i'm very sorry, fault was mine.
I don't know how, but it seems i've screwed things up in my builds or code management.
Can you test using the plugin with all my filters inside https://github.com/jpsdr/plugins_JPSDR
**Edit**
Finaly don't, i've deleted it also, i've realy messed-up the code management for the resampler between my different Visual Studio versions.

**Comment by jpsdr** [comment]
Made a new proper build this time.

**Comment by TbtBI** [comment]
I'm using [AvsPmod](https://github.com/gispos/AvsPmod) (screenshots). I downloaded and tested VIrtualDub (same results as AvsPmod) when you mentioned the VirtualDub testing. I just didn't show the VirtualDub screenshots.
Anyway, everything is OK with the new build.
@pinterf , @jpsdr, thanks for your time on this ticket.
@jpsdr, thanks for the fixes and the builds.
