### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by TbtBI** [jpsdr/ResampleMT#2]
Using [this script](https://pastebin.com/raw/UTC28zyx) I have Access Violation when cLeft and/or cRight is 8.
```
source
bbmod(x,x,8,x) #or bbmod(x,x,x,8)
```
 There is no issue if I change "StackVertical(last,c2.Crop(0,cTop*2,cWidth*2,(cHeight-cTop)*2)).PointResizeMT(cWidth,cHeight)" to "StackVertical(last,c2.Crop(0,cTop*2,cWidth*2,(cHeight-cTop)*2)).PointResize(cWidth,cHeight)".
The latest pinterf Avisynth+ x64 and masktools x64 are used.

**Comment by jpsdr** [comment]
Found issue, fix in next release.
Thanks for pointing things out.

**Comment by TbtBI** [comment]
Thanks for fixing the issue.
